stages:
  - test
  - release
  - notifications

variables:
  GIT_STRATEGY: clone

##
# Stage: test
#

.test: &test
  stage: test
  tags:
    - docker
  script: "terraform fmt -check -diff -recursive && terraform init -input=false"

0.12.13:
  <<: *test
  image:
    name: hashicorp/terraform:0.12.13
    entrypoint: [""]
0.12.12:
  <<: *test
  image:
    name: hashicorp/terraform:0.12.12
    entrypoint: [""]
0.12.11:
  <<: *test
  image:
    name: hashicorp/terraform:0.12.11
    entrypoint: [""]

##
# Stage: release

changelog:
  stage: release
  tags:
    - docker
  image:
    name: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
    entrypoint: [""]
  script:
    - release changelog
    - release --skip-ssl-verify commit-and-tag CHANGELOG.md
  when: manual
  only:
    - master

##
# Stage: notifications
# notifies both Slack and ops.lo build events

notify_slack_failure:
  stage: notifications
  when: on_failure
  except:
  dependencies: []
  before_script: []
  script:
    - /opt/scribd/bin/build_notifier.rb failed

notify_slack_success:
  stage: notifications
  when: on_success
  except:
  dependencies: []
  before_script: []
  script:
    - /opt/scribd/bin/build_notifier.rb success

