name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform Lint'
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inject provider configs for validate command'
        run: |
            cat > providers.tf <<EOF
            provider "aws" {
              region = "us-east-2"
            }

            provider "datadog" {
              api_key = ""
              app_key = ""
            }
            EOF
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: 'Release'
    if: "github.ref == 'master'"
    runs-on: ubuntu-18.04
    needs: terraform
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@~17.0.4
